### ISSUE TITLE
wireframe end-to-end website mock up

### ISSUE THREAD

**Issue by johnsantry** [Woz-U-Group-Projects/code-fusion#4]
Wireframe mockup of end to end total website top level flow

**Comment by MasterFili** [comment]
[wireframe end-to-end website mock up.pdf](https://github.com/Woz-U-Group-Projects/code-fusion/files/3075747/wireframe.end-to-end.website.mock.up.pdf)

**Comment by MasterFili** [comment]
[wireframe_end-to-end_website_mock_up.pdf](https://github.com/Woz-U-Group-Projects/code-fusion/files/3075926/wireframe_end-to-end_website_mock_up.pdf)
[wireframe end-to-end website mock up.pdf](https://github.com/Woz-U-Group-Projects/code-fusion/files/3075927/wireframe.end-to-end.website.mock.up.pdf)

**Comment by MasterFili** [comment]
[wireframe_end-to-end_website_mock_up.pdf](https://github.com/Woz-U-Group-Projects/code-fusion/files/3075929/wireframe_end-to-end_website_mock_up.pdf)
[wireframe end-to-end website mock up.pdf](https://github.com/Woz-U-Group-Projects/code-fusion/files/3075930/wireframe.end-to-end.website.mock.up.pdf)
